export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";

export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

export const FETCH_POSTS_BY_USER_ID_REQUEST = "FETCH_POSTS_BY_USER_ID_REQUEST";
export const FETCH_POSTS_BY_USER_ID_SUCCESS = "FETCH_POSTS_BY_USER_ID_SUCCESS";
export const FETCH_POSTS_BY_USER_ID_FAILURE = "FETCH_POSTS_BY_USER_ID_FAILURE";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";
