export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";

export const FETCH_POST_REQUEST = "FETCH_POST_REQUEST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILURE = "FETCH_POST_FAILURE";

export const FETCH_POSTS_BY_USER_ID_REQUEST = "FETCH_POSTS_BY_USER_ID_REQUEST";
export const FETCH_POSTS_BY_USER_ID_SUCCESS = "FETCH_POSTS_BY_USER_ID_SUCCESS";
export const FETCH_POSTS_BY_USER_ID_FAILURE = "FETCH_POSTS_BY_USER_ID_FAILURE";

export const FETCH_POST_USERS_REQUEST = "FETCH_POST_USERS_REQUEST";
export const FETCH_POST_USERS_SUCCESS = "FETCH_POST_USERS_SUCCESS";
export const FETCH_POST_USERS_FAILURE = "FETCH_POST_USERS_FAILURE";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";
