export const FETCH_COMMENTS_BY_POST_ID_REQUEST =
  "FETCH_COMMENTS_BY_POST_ID_REQUEST";
export const FETCH_COMMENTS_BY_POST_ID_SUCCESS =
  "FETCH_COMMENTS_BY_POST_ID_SUCCESS";
export const FETCH_COMMENTS_BY_POST_ID_FAILURE =
  "FETCH_COMMENTS_BY_POST_ID_FAILURE";
